### ISSUE TITLE
Do not work =(

### ISSUE THREAD

**Issue by lshamanll** [iconify/iconify-figma-plus#1]
Plugin do not work =(

**Comment by cyberalien** [comment]
What exactly doesn't work? Do you see it in menu? Does window appear?

**Comment by lshamanll** [comment]
Yes, I see, but when I click in "Add icon" or "Add and close" plugin is freezing and I cannot cancel it///
Check the video: https://monosnap.com/file/d5MCDD7FlVR21DqhVC6WOeM9p1HulH

**Comment by cyberalien** [comment]
Thanks.

Something weird is going on. Can you please try this:

1. Open Figma Plus, in top right corner there is small button. Move mouse over it, you'll see option to enable development mode. Enable development mode.

2. Uninstall Iconify plug-in and restart Figma.

3. In Figma Plus menu you'll see new option: "run script". Click it. Paste following script:
```
var el = document.createElement('script'); el.setAttribute('src', 'https://iconify.github.io/iconify-figma-plus/dist/plugin.js?t=' + Date.now()); document.head.appendChild(el);
```
and click "Run" button. This will load latest version of this plug-in directly from GitHub.

After that Iconify should appear in plug-ins list. Then please try plug-in again.

**Comment by lshamanll** [comment]
Great! It's working!)
Thanks!!

**Comment by cyberalien** [comment]
Awesome. Thanks for testing. I'll publish update.

**Comment by cyberalien** [comment]
Figma Plus guys have approved update. You can install plug-in again from Figma Plus menu and it should work correctly now.

**Comment by lshamanll** [comment]
It's really working! Thanks!
